export const EB_ADD_ACTION = 'EB_ADD_ACTION';
export const EB_CREATE = 'EB_CREATE';

export const EB_LOAD_BALANCE = 'EB_LOAD_BALANCE';
export const EB_LOAD_BALANCE_SUCCESS = 'EB_LOAD_BALANCE_SUCCESS';
export const EB_LOAD_BALANCE_FAILURE = 'EB_LOAD_BALANCE_FAILURE';

export const EB_BALANCE_INPUT_ADD = 'EB_BALANCE_INPUT_ADD';
